name = "UKSF Task Force Alpha - Temp Modpack";
author = "UKSF Taskforce Alpha Team";
logo = "z\uksfta\temp\data\icon_128_ca.paa";
logoOver = "z\uksfta\temp\data\icon_128_highlight_ca.paa";
logoSmall = "z\uksfta\temp\data\icon_64_ca.paa";
overview = "UKSF Taskforce Alpha";
picture = "z\uksfta\temp\data\title_co.paa";
tooltip = "UKSFTA";
tooltipOwned = "UKSF Taskforce Alpha";
